apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
  labels:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/instance: oauth2-proxy
    app.kubernetes.io/version: "7.15.2"
    app.kubernetes.io/component: auth-proxy
    app.kubernetes.io/part-of: auth-platform
    app.kubernetes.io/managed-by: kustomize
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.options: kube-system-modern-tls@kubernetescrd
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-https-redirect@kubernetescrd,kube-system-security-headers@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - project.com
      secretName: project-com-tls
  rules:
    - host: project.com
      http:
        paths:
          - path: /oauth2/
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy
                port:
                  name: http
