apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oauth2-proxy-secrets
spec:
  vaultAuthRef: vault-auth-auth-platform
  mount: secret
  path: oauth2-proxy/forward-auth
  refreshAfter: 60s
  type: kv-v2
  destination:
    name: oauth2-proxy-secrets
    create: true
    labels:
      app.kubernetes.io/name: oauth2-proxy
      app.kubernetes.io/component: auth-proxy
      app.kubernetes.io/managed-by: vault-secrets-operator
