apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-server
  labels:
    app.kubernetes.io/name: auth-server
    app.kubernetes.io/instance: auth-server
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: auth-platform
    app.kubernetes.io/managed-by: kustomize
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.options: kube-system-modern-tls@kubernetescrd
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-https-redirect@kubernetescrd,kube-system-security-headers@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - project.com
      secretName: project-com-tls
  rules:
    - host: project.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-server
                port:
                  name: http
