apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mnt

resources:
  - ../../../base/app/identity/auth/stateless/auth-server
  - ../../../base/managing/migration-flyway
  - networkpolicy.yaml

patches:
  - target:
      kind: Job
      name: migration-flyway
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "-1"
          argocd.argoproj.io/hook: PreSync
