apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mnt

resources:
  - ../../../base/app/identity/keycloak/stateless/keycloak
  - vault-secrets.yaml
  - keycloak-security-headers.yaml
  - ingress-public.yaml
  - ingress-admin.yaml
  - networkpolicy.yaml

patches:
  - target:
      kind: Keycloak
      name: keycloak
    path: keycloak-hostname-patch.yaml
