apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: keycloak-security-headers
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/component: identity-provider
    app.kubernetes.io/part-of: auth-platform
    app.kubernetes.io/managed-by: kustomize
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    referrerPolicy: strict-origin-when-cross-origin
