apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: keycloak-bootstrap-admin
spec:
  vaultAuthRef: vault-auth-auth-platform
  mount: secret
  type: kv-v2
  path: keycloak/bootstrap-admin
  refreshAfter: 60s
  destination:
    name: keycloak-bootstrap-admin
    create: true
    labels:
      app.kubernetes.io/name: keycloak
      app.kubernetes.io/component: identity-provider
      app.kubernetes.io/managed-by: vault-secrets-operator
