apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-project-com
  labels:
    app.kubernetes.io/name: docker-registry
    app.kubernetes.io/instance: docker-registry
    app.kubernetes.io/version: "2.8.3"
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: platform-registry
    app.kubernetes.io/managed-by: kustomize
spec:
  secretName: registry-project-com-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "false"
    labels:
      app.kubernetes.io/part-of: platform-registry
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  usages:
    - server auth
    - digital signature
    - key encipherment
  dnsNames:
    - registry.project.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
