apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: minio-tenant-env
spec:
  vaultAuthRef: vault-auth-storage
  mount: secret
  type: kv-v2
  path: minio/tenant-env
  refreshAfter: 60s
  destination:
    name: minio-tenant-env
    create: true
    labels:
      app.kubernetes.io/name: minio
      app.kubernetes.io/component: object-storage
      app.kubernetes.io/managed-by: vault-secrets-operator
