apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-postgres-sa
  labels:
    app.kubernetes.io/name: identity-postgres
    app.kubernetes.io/instance: identity-postgres
    app.kubernetes.io/version: "16.4"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: auth-platform
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: false
