apiVersion: v1
kind: ServiceAccount
metadata:
  name: migration-flyway-sa
  labels:
    app.kubernetes.io/name: migration-flyway
    app.kubernetes.io/instance: migration-flyway
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: migration
    app.kubernetes.io/part-of: auth-platform
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: false
