apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: identity-postgres-ingress-clients
  labels:
    app.kubernetes.io/name: identity-postgres
    app.kubernetes.io/instance: identity-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: auth-platform
    app.kubernetes.io/managed-by: kustomize
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: identity-postgres
      app.kubernetes.io/instance: identity-postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: keycloak
              app.kubernetes.io/managed-by: keycloak-operator
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: auth-server
              app.kubernetes.io/instance: auth-server
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: migration-flyway
              app.kubernetes.io/instance: migration-flyway
      ports:
        - protocol: TCP
          port: 5432
