apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: identity-postgres-superuser
spec:
  vaultAuthRef: vault-auth-auth-platform
  mount: secret
  type: kv-v2
  path: identity-postgres/superuser
  refreshAfter: 60s
  destination:
    name: identity-postgres-superuser
    create: true
    labels:
      app.kubernetes.io/name: identity-postgres
      app.kubernetes.io/component: database
      app.kubernetes.io/managed-by: vault-secrets-operator
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: keycloak-db-creds
spec:
  vaultAuthRef: vault-auth-auth-platform
  mount: secret
  type: kv-v2
  path: keycloak/db
  refreshAfter: 60s
  destination:
    name: keycloak-db
    create: true
    labels:
      app.kubernetes.io/name: keycloak
      app.kubernetes.io/component: database
      app.kubernetes.io/managed-by: vault-secrets-operator
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: auth-server-db-creds
spec:
  vaultAuthRef: vault-auth-auth-platform
  mount: secret
  type: kv-v2
  path: auth-server/db
  refreshAfter: 60s
  destination:
    name: auth-server-db
    create: true
    labels:
      app.kubernetes.io/name: auth-server
      app.kubernetes.io/component: database
      app.kubernetes.io/managed-by: vault-secrets-operator
    transformation:
      templates:
        SPRING_DATASOURCE_USERNAME:
          text: '{{ index .Secrets "SPRING_DATASOURCE_USERNAME" }}'
        SPRING_DATASOURCE_PASSWORD:
          text: '{{ index .Secrets "SPRING_DATASOURCE_PASSWORD" }}'
        APP_DATASOURCE_USERNAME:
          text: '{{ index .Secrets "SPRING_DATASOURCE_USERNAME" }}'
        APP_DATASOURCE_PASSWORD:
          text: '{{ index .Secrets "SPRING_DATASOURCE_PASSWORD" }}'
