apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/version: "26.0.7"
    app.kubernetes.io/component: identity-provider
    app.kubernetes.io/part-of: auth-platform
    app.kubernetes.io/managed-by: kustomize
data:
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://identity-postgres:5432/keycloak
  KC_HTTP_ENABLED: "true"
  KC_HTTP_PORT: "8080"
  KC_HTTP_MANAGEMENT_PORT: "9000"
  KC_PROXY_HEADERS: xforwarded
  KC_HOSTNAME_STRICT: "true"
  KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "false"
  KC_CACHE: ispn
  KC_CACHE_STACK: jdbc-ping
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "true"
  KC_LOG_CONSOLE_OUTPUT: json
  JAVA_OPTS_APPEND: "-XX:MaxRAMPercentage=70 -XX:InitialRAMPercentage=50 -XX:+ExitOnOutOfMemoryError"
