apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: docker-registry-ingress-intra
  labels:
    app.kubernetes.io/name: docker-registry
    app.kubernetes.io/instance: docker-registry
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: platform-registry
    app.kubernetes.io/managed-by: kustomize
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: docker-registry
      app.kubernetes.io/instance: docker-registry
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 5000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: docker-registry-ingress-traefik
  labels:
    app.kubernetes.io/name: docker-registry
    app.kubernetes.io/instance: docker-registry
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: platform-registry
    app.kubernetes.io/managed-by: kustomize
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: docker-registry
      app.kubernetes.io/instance: docker-registry
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 5000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: docker-registry-egress-minio
  labels:
    app.kubernetes.io/name: docker-registry
    app.kubernetes.io/instance: docker-registry
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: platform-registry
    app.kubernetes.io/managed-by: kustomize
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: docker-registry
      app.kubernetes.io/instance: docker-registry
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              v1.min.io/tenant: minio
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 9000
