apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mnt

resources:
  - ../../base/managing
  - networkpolicy-baseline.yaml
  - vault
  - registry
  - database
  - auth
  - keycloak
  - storage
  - test
